inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

GitHub/InsecureHashAlgorithm:
  Exclude:
    - "spec/unit/lib/hooks/plugins/request_validator/hmac_spec.rb"

Style/HashSyntax:
  Enabled: false
