inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  DisplayCopNames: true
  TargetRubyVersion: 3.4
  Exclude:
    - "bin/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

GitHub/InsecureHashAlgorithm:
  Exclude:
    - "spec/unit/lib/hooks/plugins/auth/hmac_spec.rb"
    - "spec/acceptance/acceptance_tests.rb"

GitHub/AvoidObjectSendWithDynamicMethod:
  Exclude:
    - "spec/unit/lib/hooks/core/logger_factory_spec.rb"
    - "lib/hooks/app/api.rb"

Style/HashSyntax:
  Enabled: false
