# Sample endpoint configuration for GitHub webhooks
path: /github
handler: GitHubHandler

# GitHub uses HMAC SHA256 signature validation
verify_signature:
  type: default
  secret_env_key: GITHUB_WEBHOOK_SECRET
  header: X-Hub-Signature-256
  algorithm: sha256

# Options for GitHub webhook handling
opts:
  repository: "my-org/my-repo"
  events: ["push", "pull_request", "issues"]
  branch_filter: ["main", "develop"]
