# Sample configuration for Hooks webhook server
handler_dir: ./handlers
log_level: info

# Request handling
request_limit: 1048576    # 1MB max body size
request_timeout: 15       # 15 seconds timeout

# Path configuration
root_path: /webhooks
health_path: /health
version_path: /version

# Runtime behavior
environment: development
endpoints_dir: ./config/endpoints

# Optional features
# use_catchall_route: false  # Set to true to enable catch-all route for unknown endpoints
