#! /usr/bin/env bash

set -e # prevent any kind of script failures

source script/env "$@"

KEEP_UP=false
COMPOSE_FILE="spec/acceptance/docker-compose.yml"

# check for the --keep flag
# if it exists, we will keep the docker processes up after the tests run
for arg in "$@"; do
  if [ "$arg" == "--keep" ]; then
    KEEP_UP=true
    break
  fi
done

# check to ensure docker is running
if ! docker info &> /dev/null; then
  echo -e "${RED}Docker is not running. Please start Docker and try again.${OFF}"
  exit 1
fi

echo -e "${PURPLE}[#]${OFF} ${BLUE}Killing old docker processes${OFF}"
docker compose -f "$COMPOSE_FILE" down --remove-orphans -v -t 1
docker network prune --force
docker compose -f "$COMPOSE_FILE" up --build -d

echo -e "${PURPLE}[#]${OFF} ${BLUE}Running acceptance tests${OFF}"
bundle exec rspec spec/acceptance/acceptance_tests.rb

if [ "$KEEP_UP" == "false" ]; then
  echo -e "${PURPLE}[#]${OFF} ${BLUE}Stopping docker processes${OFF}"
  docker compose -f "$COMPOSE_FILE" down --remove-orphans -v -t 1
  docker network prune --force
else
  echo -e "${PURPLE}[#]${OFF} ${BLUE}Keeping docker processes up${OFF}"
fi

echo -e "${PURPLE}[#]${OFF} ${GREEN}Acceptance tests passed${OFF}"
