#! /usr/bin/env bash

# usage: script/server [--dev]

set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd "$DIR"

# check for --dev flag
if [[ "$1" == "--dev" ]]; then
  source script/dev
  shift # remove the --dev flag from the arguments
fi

bundle exec puma -C spec/acceptance/config/puma.rb --tag hooks
