# Sample endpoint configuration for GitHub webhooks
path: /github
handler: GithubHandler

# GitHub uses HMAC SHA256 signature validation
request_validator:
  type: GitHubWebhooks
  secret_env_key: GITHUB_WEBHOOK_SECRET
  # header: X-Hub-Signature-256 # Optional, defaults to X-Hub-Signature-256
  # algorithm: sha256 # Optional, defaults to sha256

# Options for GitHub webhook handling
opts:
  slack_channel: "#github-webhooks"
