# Sample endpoint configuration for GitHub webhooks
path: /github
handler: GithubHandler

# GitHub uses HMAC SHA256 signature validation
auth:
  type: hmac
  secret_env_key: GITHUB_WEBHOOK_SECRET
  header: X-Hub-Signature-256
  algorithm: sha256
  format: "algorithm=signature"  # produces "sha256=abc123..."

# Options for GitHub webhook handling
opts:
  slack_channel: "#github-webhooks"
