path: /hmac_with_timestamp
handler: hello

auth:
  type: hmac
  secret_env_key: ALT_WEBHOOK_SECRET
  header: X-HMAC-Signature
  timestamp_header: X-HMAC-Timestamp
  timestamp_tolerance: 60 # 1 minute
  algorithm: sha256
  format: "algorithm=signature"  # produces "sha256=abc123..."
  payload_template: "{timestamp}:{body}"
