path: /ip_filtering_example
handler: hello

auth:
  type: ip_filtering_example

opts:
  allowed_ips:
    - "999.999.999.999" # intentionally invalid IP
    - "888.888.888.888" # intentionally invalid IP
