# Sample configuration for Hooks webhook server
handler_plugin_dir: ./spec/acceptance/plugins/handlers
auth_plugin_dir: ./spec/acceptance/plugins/auth
lifecycle_plugin_dir: ./spec/acceptance/plugins/lifecycle
instruments_plugin_dir: ./spec/acceptance/plugins/instruments

log_level: debug

default_format: json # default response format for the server

# Request handling
request_limit: 1048576    # 1MB max body size
request_timeout: 15       # 15 seconds timeout

# Path configuration
root_path: /webhooks
health_path: /health
version_path: /version

# Runtime behavior
# environment: development # it is better to use the environment variable RACK_ENV to control the environment

# Available endpoints
# Each endpoint configuration file should be placed in the endpoints directory
endpoints_dir: ./spec/acceptance/config/endpoints

# Optional features
# use_catchall_route: false  # Set to true to enable catch-all route for unknown endpoints
