# Sample configuration for Hooks webhook server
handler_plugin_dir: ./spec/acceptance/handlers
log_level: debug

# Request handling
request_limit: 1048576    # 1MB max body size
request_timeout: 15       # 15 seconds timeout

# Path configuration
root_path: /webhooks
health_path: /health
version_path: /version

# Runtime behavior
environment: development

# Available endpoints
# Each endpoint configuration file should be placed in the endpoints directory
endpoints_dir: ./spec/acceptance/config/endpoints

# Optional features
# use_catchall_route: false  # Set to true to enable catch-all route for unknown endpoints
