name: acceptance

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  acceptance:
    name: acceptance
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1

      - uses: ruby/setup-ruby@ac793fdd38cc468a4dd57246fa9d0e868aba9085 # pin@v1.270.0
        with:
          bundler-cache: true

      - name: bootstrap
        run: script/bootstrap

      - name: acceptance
        run: script/acceptance
