name: integration

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2.2', '3.2.3', '3.3.0', '3.3.1', '3.4.0', '3.4.2', '3.4.3', '3.4.4' ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ruby/setup-ruby@a4effe49ee8ee5b8b5091268c473a4628afb5651 # pin@v1.245.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: bootstrap
        run: script/bootstrap

      - name: integration
        run: script/integration
